-- V10: 创建业务模型与字段定义表（用于数据模型管理模块）
-- 表设计说明：
-- BUSINESS_MODEL 保存模型元信息（如模型名称、物理表名、描述、创建信息等）
-- BUSINESS_FIELD 保存每个模型的字段定义（如字段名、列名、类型、长度、是否主键、是否可空、注释、排序等）

CREATE TABLE BUSINESS_MODEL (
    ID VARCHAR2(64) PRIMARY KEY,
    NAME VARCHAR2(200) NOT NULL,
    TABLE_NAME VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    CREATED_BY VARCHAR2(64),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR2(64),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 为 BUSINESS_MODEL 创建唯一索引，保证物理表名唯一
CREATE UNIQUE INDEX UQ_BUSINESS_MODEL_TABLE_NAME ON BUSINESS_MODEL(TABLE_NAME);

-- 表与列注释（中文）
COMMENT ON TABLE BUSINESS_MODEL IS '业务模型表：保存模型元数据（如用户模型、订单模型等）';
COMMENT ON COLUMN BUSINESS_MODEL.ID IS '主键，UUID';
COMMENT ON COLUMN BUSINESS_MODEL.NAME IS '模型显示名称，如：用户、订单';
COMMENT ON COLUMN BUSINESS_MODEL.TABLE_NAME IS '物理表名，如：users、orders（建议小写下划线）';
COMMENT ON COLUMN BUSINESS_MODEL.DESCRIPTION IS '模型描述/备注';
COMMENT ON COLUMN BUSINESS_MODEL.CREATED_BY IS '创建者用户ID';
COMMENT ON COLUMN BUSINESS_MODEL.CREATED_AT IS '创建时间';
COMMENT ON COLUMN BUSINESS_MODEL.UPDATED_BY IS '更新者用户ID';
COMMENT ON COLUMN BUSINESS_MODEL.UPDATED_AT IS '更新时间';

CREATE TABLE BUSINESS_FIELD (
    ID VARCHAR2(64) PRIMARY KEY,
    MODEL_ID VARCHAR2(64) NOT NULL,
    FIELD_NAME VARCHAR2(200) NOT NULL,
    COLUMN_NAME VARCHAR2(200) NOT NULL,
    DATA_TYPE VARCHAR2(50) NOT NULL,
    LENGTH NUMBER(10),
    IS_PRIMARY NUMBER(1) DEFAULT 0,
    IS_NULLABLE NUMBER(1) DEFAULT 1,
    FIELD_COMMENT VARCHAR2(1000),
    DEFAULT_VALUE VARCHAR2(1000),
    IS_UNIQUE NUMBER(1) DEFAULT 0,
    IS_INDEXED NUMBER(1) DEFAULT 0,
    SORT_ORDER NUMBER(10) DEFAULT 0,
    CREATED_BY VARCHAR2(64),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR2(64),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 为 BUSINESS_FIELD 建立索引，便于按模型查询字段
CREATE INDEX IDX_BUSINESS_FIELD_MODEL_ID ON BUSINESS_FIELD(MODEL_ID);

COMMENT ON TABLE BUSINESS_FIELD IS '业务模型字段表：保存模型下每个字段的定义';
COMMENT ON COLUMN BUSINESS_FIELD.ID IS '主键，UUID';
COMMENT ON COLUMN BUSINESS_FIELD.MODEL_ID IS '关联 BUSINESS_MODEL.ID';
COMMENT ON COLUMN BUSINESS_FIELD.FIELD_NAME IS '字段显示名称，如：用户名、金额';
COMMENT ON COLUMN BUSINESS_FIELD.COLUMN_NAME IS '物理列名，如：username、amount';
COMMENT ON COLUMN BUSINESS_FIELD.DATA_TYPE IS '数据类型枚举，如：VARCHAR、INT、DECIMAL、DATE、DATETIME、BOOLEAN、TEXT';
COMMENT ON COLUMN BUSINESS_FIELD.LENGTH IS '长度或精度（依据类型含义）';
COMMENT ON COLUMN BUSINESS_FIELD.IS_PRIMARY IS '是否为主键：1=是，0=否';
COMMENT ON COLUMN BUSINESS_FIELD.IS_NULLABLE IS '是否可空：1=可空，0=不可空';
COMMENT ON COLUMN BUSINESS_FIELD.FIELD_COMMENT IS '字段备注/注释';
COMMENT ON COLUMN BUSINESS_FIELD.DEFAULT_VALUE IS '字段默认值（文本形式）';
COMMENT ON COLUMN BUSINESS_FIELD.IS_UNIQUE IS '字段是否唯一：1=唯一，0=非唯一';
COMMENT ON COLUMN BUSINESS_FIELD.IS_INDEXED IS '字段是否建索引：1=建索引，0=不建索引';
COMMENT ON COLUMN BUSINESS_FIELD.SORT_ORDER IS '字段排序，用于展示顺序';
COMMENT ON COLUMN BUSINESS_FIELD.CREATED_BY IS '创建者用户ID';
COMMENT ON COLUMN BUSINESS_FIELD.CREATED_AT IS '创建时间';
COMMENT ON COLUMN BUSINESS_FIELD.UPDATED_BY IS '更新者用户ID';
COMMENT ON COLUMN BUSINESS_FIELD.UPDATED_AT IS '更新时间';

