-- V11: 创建系统菜单表与角色-菜单关联表

CREATE TABLE SYS_MENU (
  ID VARCHAR2(64) PRIMARY KEY,
  TITLE VARCHAR2(256) NOT NULL,
  PATH VARCHAR2(512),
  PARENT_ID VARCHAR2(64),
  ICON VARCHAR2(128),
  ORDER_NUM NUMBER(10) DEFAULT 0,
  CREATED_BY VARCHAR2(64),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR2(64),
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE SYS_MENU IS '系统菜单表';
COMMENT ON COLUMN SYS_MENU.ID IS '主键，UUID';
COMMENT ON COLUMN SYS_MENU.TITLE IS '菜单标题';
COMMENT ON COLUMN SYS_MENU.PATH IS '前端路由路径';
COMMENT ON COLUMN SYS_MENU.PARENT_ID IS '父菜单ID';
COMMENT ON COLUMN SYS_MENU.ICON IS '图标名称';
COMMENT ON COLUMN SYS_MENU.ORDER_NUM IS '排序值';
COMMENT ON COLUMN SYS_MENU.CREATED_BY IS '创建者用户ID';
COMMENT ON COLUMN SYS_MENU.CREATED_AT IS '创建时间';
COMMENT ON COLUMN SYS_MENU.UPDATED_BY IS '更新者用户ID';
COMMENT ON COLUMN SYS_MENU.UPDATED_AT IS '更新时间';

CREATE TABLE SYS_ROLE_MENU (
  ID VARCHAR2(64) PRIMARY KEY,
  ROLE_ID VARCHAR2(64) NOT NULL,
  MENU_ID VARCHAR2(64) NOT NULL,
  CREATED_BY VARCHAR2(64),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR2(64),
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX UQ_SYS_ROLE_MENU ON SYS_ROLE_MENU(ROLE_ID, MENU_ID);

COMMENT ON TABLE SYS_ROLE_MENU IS '角色-菜单关联表';
COMMENT ON COLUMN SYS_ROLE_MENU.ID IS '主键，UUID';
COMMENT ON COLUMN SYS_ROLE_MENU.ROLE_ID IS '角色ID';
COMMENT ON COLUMN SYS_ROLE_MENU.MENU_ID IS '菜单ID';
COMMENT ON COLUMN SYS_ROLE_MENU.CREATED_BY IS '创建者用户ID';
COMMENT ON COLUMN SYS_ROLE_MENU.CREATED_AT IS '创建时间';
COMMENT ON COLUMN SYS_ROLE_MENU.UPDATED_BY IS '更新者用户ID';
COMMENT ON COLUMN SYS_ROLE_MENU.UPDATED_AT IS '更新时间';

