
-- V13: 创建外部系统注册表
CREATE TABLE SYS_EXTERNAL_SYSTEM (
  ID VARCHAR2(64) PRIMARY KEY,
  NAME VARCHAR2(255) NOT NULL,
  DESCRIPTION CLOB,
  ADDRESS VARCHAR2(255) NOT NULL,
  PORT NUMBER(10),
  SYSTEM_CODE VARCHAR2(128) NOT NULL,
  ATTACHMENT_IDS CLOB,
  CREATED_BY VARCHAR2(64),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR2(64),
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE SYS_EXTERNAL_SYSTEM IS '外部系统注册表，用于保存可被本平台调用/管理的外部系统信息';
COMMENT ON COLUMN SYS_EXTERNAL_SYSTEM.ID IS '主键，UUID';
COMMENT ON COLUMN SYS_EXTERNAL_SYSTEM.NAME IS '系统名称';
COMMENT ON COLUMN SYS_EXTERNAL_SYSTEM.DESCRIPTION IS '系统描述';
COMMENT ON COLUMN SYS_EXTERNAL_SYSTEM.ADDRESS IS '地址（IP或域名）';
COMMENT ON COLUMN SYS_EXTERNAL_SYSTEM.PORT IS '端口号';
COMMENT ON COLUMN SYS_EXTERNAL_SYSTEM.SYSTEM_CODE IS '系统编码（业务使用）';
COMMENT ON COLUMN SYS_EXTERNAL_SYSTEM.ATTACHMENT_IDS IS '附件ID列表（逗号分隔，引用 sys_file_object.id）';
COMMENT ON COLUMN SYS_EXTERNAL_SYSTEM.CREATED_BY IS '创建者用户ID';
COMMENT ON COLUMN SYS_EXTERNAL_SYSTEM.CREATED_AT IS '创建时间';
COMMENT ON COLUMN SYS_EXTERNAL_SYSTEM.UPDATED_BY IS '更新者用户ID';
COMMENT ON COLUMN SYS_EXTERNAL_SYSTEM.UPDATED_AT IS '更新时间';

