-- V14: 创建系统接口表
CREATE TABLE SYS_SYSTEM_API (
  ID VARCHAR2(64) PRIMARY KEY,
  SYSTEM_ID VARCHAR2(64) NOT NULL,
  API_NAME VARCHAR2(255) NOT NULL,
  METHOD VARCHAR2(16),
  URL VARCHAR2(1024),
  DESCRIPTION CLOB,
  REQUEST_EXAMPLE CLOB,
  RESPONSE_EXAMPLE CLOB,
  REQ_FIELD_COMMENT CLOB,
  RES_FIELD_COMMENT CLOB,
  ATTACHMENT_IDS CLOB,
  CREATED_BY VARCHAR2(64),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR2(64),
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE SYS_SYSTEM_API IS '外部系统接口表，用于保存外部系统下的接口定义';
COMMENT ON COLUMN SYS_SYSTEM_API.ID IS '主键，UUID';
COMMENT ON COLUMN SYS_SYSTEM_API.SYSTEM_ID IS '关联系统ID，引用 SYS_EXTERNAL_SYSTEM.ID';
COMMENT ON COLUMN SYS_SYSTEM_API.API_NAME IS '接口名称';
COMMENT ON COLUMN SYS_SYSTEM_API.METHOD IS '请求类型，如 GET/POST';
COMMENT ON COLUMN SYS_SYSTEM_API.URL IS '接口地址';
COMMENT ON COLUMN SYS_SYSTEM_API.DESCRIPTION IS '接口详情';
COMMENT ON COLUMN SYS_SYSTEM_API.REQUEST_EXAMPLE IS '请求示例';
COMMENT ON COLUMN SYS_SYSTEM_API.RESPONSE_EXAMPLE IS '响应示例';
COMMENT ON COLUMN SYS_SYSTEM_API.REQ_FIELD_COMMENT IS '请求字段注释';
COMMENT ON COLUMN SYS_SYSTEM_API.RES_FIELD_COMMENT IS '响应字段注释';
COMMENT ON COLUMN SYS_SYSTEM_API.ATTACHMENT_IDS IS '附件ID列表（逗号分隔，引用 SYS_FILE_OBJECT.ID）';
COMMENT ON COLUMN SYS_SYSTEM_API.CREATED_BY IS '创建者用户ID';
COMMENT ON COLUMN SYS_SYSTEM_API.CREATED_AT IS '创建时间';
COMMENT ON COLUMN SYS_SYSTEM_API.UPDATED_BY IS '更新者用户ID';
COMMENT ON COLUMN SYS_SYSTEM_API.UPDATED_AT IS '更新时间';

