CREATE TABLE SYS_DATA_SOURCE (
    ID                VARCHAR(64)   NOT NULL,
    CREATED_BY        VARCHAR(64),
    UPDATED_BY        VARCHAR(64),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NAME              VARCHAR(128)  NOT NULL,
    DRIVER_CLASS_NAME VARCHAR(255)  NOT NULL,
    URL               VARCHAR(512)  NOT NULL,
    USERNAME          VARCHAR(128),
    PASSWORD          VARCHAR(256),
    STATUS            INT DEFAULT 1,
    CONNECTIVITY      INT DEFAULT 2,
    CONSTRAINT PK_SYS_DATA_SOURCE PRIMARY KEY (ID)
);

COMMENT ON TABLE SYS_DATA_SOURCE IS '数据源配置表';
COMMENT ON COLUMN SYS_DATA_SOURCE.ID IS '主键ID';
COMMENT ON COLUMN SYS_DATA_SOURCE.CREATED_BY IS '创建人';
COMMENT ON COLUMN SYS_DATA_SOURCE.UPDATED_BY IS '更新人';
COMMENT ON COLUMN SYS_DATA_SOURCE.CREATED_AT IS '创建时间，格式：yyyy-MM-dd HH:mm:ss';
COMMENT ON COLUMN SYS_DATA_SOURCE.UPDATED_AT IS '更新时间，格式：yyyy-MM-dd HH:mm:ss';
COMMENT ON COLUMN SYS_DATA_SOURCE.NAME IS '数据源名称';
COMMENT ON COLUMN SYS_DATA_SOURCE.DRIVER_CLASS_NAME IS 'JDBC驱动类名';
COMMENT ON COLUMN SYS_DATA_SOURCE.URL IS '数据源连接URL';
COMMENT ON COLUMN SYS_DATA_SOURCE.USERNAME IS '用户名';
COMMENT ON COLUMN SYS_DATA_SOURCE.PASSWORD IS '密码';
COMMENT ON COLUMN SYS_DATA_SOURCE.STATUS IS '状态：1-启用，0-禁用';
COMMENT ON COLUMN SYS_DATA_SOURCE.CONNECTIVITY IS '连通性：1-链接，2-断开';