CREATE TABLE WF_PROCESS_DEF (
    ID            VARCHAR(64)   NOT NULL,
    CREATED_BY    VARCHAR(64),
    UPDATED_BY    VARCHAR(64),
    CREATED_AT    TIMESTAMP,
    UPDATED_AT    TIMESTAMP,
    CODE          VARCHAR(64)   NOT NULL,
    NAME          VARCHAR(128)  NOT NULL,
    VERSION_NO    INT           NOT NULL,
    STATUS        INT DEFAULT 1 NOT NULL,
    IS_LATEST     INT DEFAULT 1 NOT NULL,
    REMARK        VARCHAR(512),
    CONSTRAINT PK_WF_PROCESS_DEF PRIMARY KEY (ID),
    CONSTRAINT UK_WF_PROCESS_DEF_CODE_VER UNIQUE (CODE, VERSION_NO)
);

COMMENT ON TABLE WF_PROCESS_DEF IS '流程定义主表（版本化）';
COMMENT ON COLUMN WF_PROCESS_DEF.ID IS '主键ID';
COMMENT ON COLUMN WF_PROCESS_DEF.CREATED_BY IS '创建人';
COMMENT ON COLUMN WF_PROCESS_DEF.UPDATED_BY IS '更新人';
COMMENT ON COLUMN WF_PROCESS_DEF.CREATED_AT IS '创建时间';
COMMENT ON COLUMN WF_PROCESS_DEF.UPDATED_AT IS '更新时间';
COMMENT ON COLUMN WF_PROCESS_DEF.CODE IS '流程编码（同一流程跨版本共享）';
COMMENT ON COLUMN WF_PROCESS_DEF.NAME IS '流程名称';
COMMENT ON COLUMN WF_PROCESS_DEF.VERSION_NO IS '流程版本号，从1开始递增';
COMMENT ON COLUMN WF_PROCESS_DEF.STATUS IS '定义状态：1-启用，0-停用';
COMMENT ON COLUMN WF_PROCESS_DEF.IS_LATEST IS '是否最新版本：1-是，0-否';
COMMENT ON COLUMN WF_PROCESS_DEF.REMARK IS '定义备注';

CREATE TABLE WF_PROCESS_NODE_DEF (
    ID              VARCHAR(64)   NOT NULL,
    CREATED_BY      VARCHAR(64),
    UPDATED_BY      VARCHAR(64),
    CREATED_AT      TIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    DEF_ID          VARCHAR(64)   NOT NULL,
    NODE_KEY        VARCHAR(64)   NOT NULL,
    NODE_NAME       VARCHAR(128)  NOT NULL,
    SORT_NO         INT           NOT NULL,
    APPROVAL_MODE   VARCHAR(32)   NOT NULL,
    ASSIGNEE_EXPR   VARCHAR(512)  NOT NULL,
    CONSTRAINT PK_WF_PROCESS_NODE_DEF PRIMARY KEY (ID)
);

CREATE INDEX IDX_WF_NODE_DEF_DEF_SORT ON WF_PROCESS_NODE_DEF (DEF_ID, SORT_NO);

COMMENT ON TABLE WF_PROCESS_NODE_DEF IS '流程节点定义';
COMMENT ON COLUMN WF_PROCESS_NODE_DEF.ID IS '主键ID';
COMMENT ON COLUMN WF_PROCESS_NODE_DEF.CREATED_BY IS '创建人';
COMMENT ON COLUMN WF_PROCESS_NODE_DEF.UPDATED_BY IS '更新人';
COMMENT ON COLUMN WF_PROCESS_NODE_DEF.CREATED_AT IS '创建时间';
COMMENT ON COLUMN WF_PROCESS_NODE_DEF.UPDATED_AT IS '更新时间';
COMMENT ON COLUMN WF_PROCESS_NODE_DEF.DEF_ID IS '所属流程定义ID';
COMMENT ON COLUMN WF_PROCESS_NODE_DEF.NODE_KEY IS '节点编码（定义内唯一）';
COMMENT ON COLUMN WF_PROCESS_NODE_DEF.NODE_NAME IS '节点名称';
COMMENT ON COLUMN WF_PROCESS_NODE_DEF.SORT_NO IS '节点顺序号（升序流转）';
COMMENT ON COLUMN WF_PROCESS_NODE_DEF.APPROVAL_MODE IS '审批模式：BASIC/OR_SIGN/COUNTER_SIGN';
COMMENT ON COLUMN WF_PROCESS_NODE_DEF.ASSIGNEE_EXPR IS '审批人表达式，当前以逗号分隔账号';

CREATE TABLE WF_PROCESS_INST (
    ID               VARCHAR(64)   NOT NULL,
    CREATED_BY       VARCHAR(64),
    UPDATED_BY       VARCHAR(64),
    CREATED_AT       TIMESTAMP,
    UPDATED_AT       TIMESTAMP,
    DEF_ID           VARCHAR(64)   NOT NULL,
    DEF_CODE         VARCHAR(64)   NOT NULL,
    DEF_VERSION      INT           NOT NULL,
    BIZ_TYPE         VARCHAR(64)   NOT NULL,
    BIZ_ID           VARCHAR(64)   NOT NULL,
    STATE            VARCHAR(32)   NOT NULL,
    CURRENT_NODE_KEY VARCHAR(64),
    STARTER          VARCHAR(64)   NOT NULL,
    VARIABLES_JSON   CLOB,
    REVISION         INT DEFAULT 0 NOT NULL,
    CONSTRAINT PK_WF_PROCESS_INST PRIMARY KEY (ID)
);

CREATE INDEX IDX_WF_INST_BIZ ON WF_PROCESS_INST (BIZ_TYPE, BIZ_ID);
CREATE INDEX IDX_WF_INST_STATE ON WF_PROCESS_INST (STATE);

COMMENT ON TABLE WF_PROCESS_INST IS '流程实例';
COMMENT ON COLUMN WF_PROCESS_INST.ID IS '主键ID';
COMMENT ON COLUMN WF_PROCESS_INST.CREATED_BY IS '创建人';
COMMENT ON COLUMN WF_PROCESS_INST.UPDATED_BY IS '更新人';
COMMENT ON COLUMN WF_PROCESS_INST.CREATED_AT IS '创建时间';
COMMENT ON COLUMN WF_PROCESS_INST.UPDATED_AT IS '更新时间';
COMMENT ON COLUMN WF_PROCESS_INST.DEF_ID IS '关联流程定义ID';
COMMENT ON COLUMN WF_PROCESS_INST.DEF_CODE IS '流程编码（冗余便于查询）';
COMMENT ON COLUMN WF_PROCESS_INST.DEF_VERSION IS '流程定义版本号（实例绑定）';
COMMENT ON COLUMN WF_PROCESS_INST.BIZ_TYPE IS '业务类型（引擎不感知具体业务）';
COMMENT ON COLUMN WF_PROCESS_INST.BIZ_ID IS '业务单据ID';
COMMENT ON COLUMN WF_PROCESS_INST.STATE IS '流程状态：DRAFT/RUNNING/COMPLETED/TERMINATED/WITHDRAWN';
COMMENT ON COLUMN WF_PROCESS_INST.CURRENT_NODE_KEY IS '当前节点编码，结束时为空';
COMMENT ON COLUMN WF_PROCESS_INST.STARTER IS '流程发起人';
COMMENT ON COLUMN WF_PROCESS_INST.VARIABLES_JSON IS '流程变量JSON';
COMMENT ON COLUMN WF_PROCESS_INST.REVISION IS '乐观锁版本号';

CREATE TABLE WF_TASK_INST (
    ID               VARCHAR(64)   NOT NULL,
    CREATED_BY       VARCHAR(64),
    UPDATED_BY       VARCHAR(64),
    CREATED_AT       TIMESTAMP,
    UPDATED_AT       TIMESTAMP,
    INSTANCE_ID      VARCHAR(64)   NOT NULL,
    NODE_KEY         VARCHAR(64)   NOT NULL,
    ASSIGNEE         VARCHAR(64)   NOT NULL,
    STATE            VARCHAR(32)   NOT NULL,
    VOTE_RESULT      VARCHAR(32),
    DELEGATED_FROM   VARCHAR(64),
    COMPLETED_AT     TIMESTAMP,
    REVISION         INT DEFAULT 0 NOT NULL,
    CONSTRAINT PK_WF_TASK_INST PRIMARY KEY (ID)
);

CREATE INDEX IDX_WF_TASK_INST_NODE ON WF_TASK_INST (INSTANCE_ID, NODE_KEY);
CREATE INDEX IDX_WF_TASK_ASSIGNEE ON WF_TASK_INST (ASSIGNEE, STATE);

COMMENT ON TABLE WF_TASK_INST IS '任务实例';
COMMENT ON COLUMN WF_TASK_INST.ID IS '主键ID';
COMMENT ON COLUMN WF_TASK_INST.CREATED_BY IS '创建人';
COMMENT ON COLUMN WF_TASK_INST.UPDATED_BY IS '更新人';
COMMENT ON COLUMN WF_TASK_INST.CREATED_AT IS '创建时间';
COMMENT ON COLUMN WF_TASK_INST.UPDATED_AT IS '更新时间';
COMMENT ON COLUMN WF_TASK_INST.INSTANCE_ID IS '所属流程实例ID';
COMMENT ON COLUMN WF_TASK_INST.NODE_KEY IS '所属节点编码';
COMMENT ON COLUMN WF_TASK_INST.ASSIGNEE IS '当前处理人';
COMMENT ON COLUMN WF_TASK_INST.STATE IS '任务状态：PENDING/APPROVED/REJECTED/TRANSFERRED/CANCELLED';
COMMENT ON COLUMN WF_TASK_INST.VOTE_RESULT IS '审批结果：PASS/REJECT';
COMMENT ON COLUMN WF_TASK_INST.DELEGATED_FROM IS '移交来源人';
COMMENT ON COLUMN WF_TASK_INST.COMPLETED_AT IS '任务处理完成时间';
COMMENT ON COLUMN WF_TASK_INST.REVISION IS '乐观锁版本号';

CREATE TABLE WF_ACTION_LOG (
    ID             VARCHAR(64)    NOT NULL,
    CREATED_BY     VARCHAR(64),
    UPDATED_BY     VARCHAR(64),
    CREATED_AT     TIMESTAMP,
    UPDATED_AT     TIMESTAMP,
    INSTANCE_ID    VARCHAR(64)    NOT NULL,
    TASK_ID        VARCHAR(64),
    ACTION_TYPE    VARCHAR(32)    NOT NULL,
    OPERATOR       VARCHAR(64)    NOT NULL,
    ACTION_COMMENT VARCHAR(1000),
    SNAPSHOT_JSON  CLOB,
    CONSTRAINT PK_WF_ACTION_LOG PRIMARY KEY (ID)
);

CREATE INDEX IDX_WF_ACTION_LOG_INST ON WF_ACTION_LOG (INSTANCE_ID);

COMMENT ON TABLE WF_ACTION_LOG IS '流程动作日志';
COMMENT ON COLUMN WF_ACTION_LOG.ID IS '主键ID';
COMMENT ON COLUMN WF_ACTION_LOG.CREATED_BY IS '创建人';
COMMENT ON COLUMN WF_ACTION_LOG.UPDATED_BY IS '更新人';
COMMENT ON COLUMN WF_ACTION_LOG.CREATED_AT IS '创建时间';
COMMENT ON COLUMN WF_ACTION_LOG.UPDATED_AT IS '更新时间';
COMMENT ON COLUMN WF_ACTION_LOG.INSTANCE_ID IS '流程实例ID';
COMMENT ON COLUMN WF_ACTION_LOG.TASK_ID IS '任务ID（发起/终止等无任务场景可为空）';
COMMENT ON COLUMN WF_ACTION_LOG.ACTION_TYPE IS '动作类型：SUBMIT/APPROVE/REJECT/TRANSFER/WITHDRAW/TERMINATE';
COMMENT ON COLUMN WF_ACTION_LOG.OPERATOR IS '操作人';
COMMENT ON COLUMN WF_ACTION_LOG.ACTION_COMMENT IS '动作备注';
COMMENT ON COLUMN WF_ACTION_LOG.SNAPSHOT_JSON IS '动作快照JSON';

CREATE TABLE WF_IDEMPOTENT (
    ID             VARCHAR(64)   NOT NULL,
    CREATED_BY     VARCHAR(64),
    UPDATED_BY     VARCHAR(64),
    CREATED_AT     TIMESTAMP,
    UPDATED_AT     TIMESTAMP,
    REQUEST_ID     VARCHAR(128)  NOT NULL,
    ACTION_TYPE    VARCHAR(32)   NOT NULL,
    INSTANCE_ID    VARCHAR(64)   NOT NULL,
    RESPONSE_JSON  CLOB,
    CONSTRAINT PK_WF_IDEMPOTENT PRIMARY KEY (ID),
    CONSTRAINT UK_WF_IDEMPOTENT_REQ UNIQUE (REQUEST_ID, ACTION_TYPE)
);


COMMENT ON TABLE WF_IDEMPOTENT IS '幂等记录表';
COMMENT ON COLUMN WF_IDEMPOTENT.ID IS '主键ID';
COMMENT ON COLUMN WF_IDEMPOTENT.CREATED_BY IS '创建人';
COMMENT ON COLUMN WF_IDEMPOTENT.UPDATED_BY IS '更新人';
COMMENT ON COLUMN WF_IDEMPOTENT.CREATED_AT IS '创建时间';
COMMENT ON COLUMN WF_IDEMPOTENT.UPDATED_AT IS '更新时间';
COMMENT ON COLUMN WF_IDEMPOTENT.REQUEST_ID IS '请求幂等ID';
COMMENT ON COLUMN WF_IDEMPOTENT.ACTION_TYPE IS '动作类型';
COMMENT ON COLUMN WF_IDEMPOTENT.INSTANCE_ID IS '流程实例ID';
COMMENT ON COLUMN WF_IDEMPOTENT.RESPONSE_JSON IS '幂等命中时返回的响应快照';

CREATE TABLE WF_CODE_SEQ (
                             SEQ_DATE VARCHAR(8) NOT NULL,
                             LAST_SEQ INT DEFAULT 0 NOT NULL,
                             CONSTRAINT PK_WF_CODE_SEQ PRIMARY KEY (SEQ_DATE)
);

COMMENT ON TABLE WF_CODE_SEQ IS '每日编码序列表，用于生成流程定义编码的日内自增序号';
COMMENT ON COLUMN WF_CODE_SEQ.SEQ_DATE IS '日期（yyyyMMdd）';
COMMENT ON COLUMN WF_CODE_SEQ.LAST_SEQ IS '当前最大序号';

CREATE TABLE WF_PROCESS_DEF_DESIGN (
                                       DEF_ID VARCHAR(64) NOT NULL,
                                       DESIGN_JSON CLOB,
                                       UPDATED_AT TIMESTAMP,
                                       CONSTRAINT PK_WF_PROCESS_DEF_DESIGN PRIMARY KEY (DEF_ID)
);

COMMENT ON TABLE WF_PROCESS_DEF_DESIGN IS '流程定义设计数据表，存储可视化设计的 JSON';
COMMENT ON COLUMN WF_PROCESS_DEF_DESIGN.DEF_ID IS '流程定义 ID';
COMMENT ON COLUMN WF_PROCESS_DEF_DESIGN.DESIGN_JSON IS '设计数据 JSON';
