CREATE TABLE WF_CODE_SEQ (
    SEQ_DATE VARCHAR(8) NOT NULL,
    LAST_SEQ INT DEFAULT 0 NOT NULL,
    CONSTRAINT PK_WF_CODE_SEQ PRIMARY KEY (SEQ_DATE)
);

COMMENT ON TABLE WF_CODE_SEQ IS '每日编码序列表，用于生成流程定义编码的日内自增序号';
COMMENT ON COLUMN WF_CODE_SEQ.SEQ_DATE IS '日期（yyyyMMdd）';
COMMENT ON COLUMN WF_CODE_SEQ.LAST_SEQ IS '当前最大序号';

