-- V3: 创建用户模块表（表名与字段使用大写，并添加表注释与字段注释）
-- Tables: SYS_USER, SYS_ROLE, SYS_PERMISSION, SYS_USER_ROLE, SYS_ROLE_PERMISSION, SYS_SESSION, SYS_AUDIT_LOG, SYS_TOKEN_BLACKLIST

CREATE TABLE SYS_USER (
                          ID VARCHAR2(64) PRIMARY KEY,
                          USERNAME VARCHAR2(128) NOT NULL,
                          PASSWORD VARCHAR2(256) NOT NULL,
                          SALT VARCHAR2(64),
                          DISPLAY_NAME VARCHAR2(128),
                          EMAIL VARCHAR2(256),
                          MOBILE VARCHAR2(32),
                          STATUS NUMBER(1) DEFAULT 1,
                          IS_SUPER NUMBER(1) DEFAULT 0,
                          CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          CREATED_BY VARCHAR2(64),
                          UPDATED_BY VARCHAR2(64)
);

CREATE UNIQUE INDEX UQ_SYS_USER_USERNAME ON SYS_USER(USERNAME);

COMMENT ON TABLE SYS_USER IS '用户表';
COMMENT ON COLUMN SYS_USER.ID IS '主键，UUID';
COMMENT ON COLUMN SYS_USER.USERNAME IS '登录用户名';
COMMENT ON COLUMN SYS_USER.PASSWORD IS '加密后的密码';
COMMENT ON COLUMN SYS_USER.SALT IS '密码盐';
COMMENT ON COLUMN SYS_USER.DISPLAY_NAME IS '展示名称/昵称';
COMMENT ON COLUMN SYS_USER.EMAIL IS '电子邮箱';
COMMENT ON COLUMN SYS_USER.MOBILE IS '手机号码';
COMMENT ON COLUMN SYS_USER.STATUS IS '用户状态，1=正常，0=禁用';
COMMENT ON COLUMN SYS_USER.IS_SUPER IS '是否为超级管理员，1=是，0=否';
COMMENT ON COLUMN SYS_USER.CREATED_AT IS '创建时间';
COMMENT ON COLUMN SYS_USER.UPDATED_AT IS '更新时间';
COMMENT ON COLUMN SYS_USER.CREATED_BY IS '创建者用户ID';
COMMENT ON COLUMN SYS_USER.UPDATED_BY IS '更新者用户ID';

CREATE TABLE SYS_ROLE (
                          ID VARCHAR2(64) PRIMARY KEY,
                          NAME VARCHAR2(128) NOT NULL,
                          CODE VARCHAR2(128) NOT NULL,
                          DESCRIPTION VARCHAR2(512),
                          CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX UQ_SYS_ROLE_CODE ON SYS_ROLE(CODE);

COMMENT ON TABLE SYS_ROLE IS '角色表';
COMMENT ON COLUMN SYS_ROLE.ID IS '主键，UUID';
COMMENT ON COLUMN SYS_ROLE.NAME IS '角色名称';
COMMENT ON COLUMN SYS_ROLE.CODE IS '角色编码（唯一）';
COMMENT ON COLUMN SYS_ROLE.DESCRIPTION IS '角色描述';
COMMENT ON COLUMN SYS_ROLE.CREATED_AT IS '创建时间';

CREATE TABLE SYS_PERMISSION (
                                ID VARCHAR2(64) PRIMARY KEY,
                                NAME VARCHAR2(128) NOT NULL,
                                RESOURCE VARCHAR2(256),
                                ACTION VARCHAR2(128),
                                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE SYS_PERMISSION IS '权限表';
COMMENT ON COLUMN SYS_PERMISSION.ID IS '主键，UUID';
COMMENT ON COLUMN SYS_PERMISSION.NAME IS '权限名称';
COMMENT ON COLUMN SYS_PERMISSION.RESOURCE IS '资源路径或资源标识';
COMMENT ON COLUMN SYS_PERMISSION.ACTION IS '操作名称，如 GET/POST 或自定义动作';
COMMENT ON COLUMN SYS_PERMISSION.CREATED_AT IS '创建时间';

CREATE TABLE SYS_USER_ROLE (
                               ID VARCHAR2(64) PRIMARY KEY,
                               USER_ID VARCHAR2(64) NOT NULL,
                               ROLE_ID VARCHAR2(64) NOT NULL,
                               CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX UQ_SYS_USER_ROLE ON SYS_USER_ROLE(USER_ID, ROLE_ID);

COMMENT ON TABLE SYS_USER_ROLE IS '用户-角色关联表';
COMMENT ON COLUMN SYS_USER_ROLE.ID IS '主键，UUID';
COMMENT ON COLUMN SYS_USER_ROLE.USER_ID IS '用户ID，引用 SYS_USER.ID';
COMMENT ON COLUMN SYS_USER_ROLE.ROLE_ID IS '角色ID，引用 SYS_ROLE.ID';
COMMENT ON COLUMN SYS_USER_ROLE.CREATED_AT IS '创建时间';

CREATE TABLE SYS_ROLE_PERMISSION (
                                     ID VARCHAR2(64) PRIMARY KEY,
                                     ROLE_ID VARCHAR2(64) NOT NULL,
                                     PERMISSION_ID VARCHAR2(64) NOT NULL,
                                     CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX UQ_SYS_ROLE_PERMISSION ON SYS_ROLE_PERMISSION(ROLE_ID, PERMISSION_ID);

COMMENT ON TABLE SYS_ROLE_PERMISSION IS '角色-权限关联表';
COMMENT ON COLUMN SYS_ROLE_PERMISSION.ID IS '主键，UUID';
COMMENT ON COLUMN SYS_ROLE_PERMISSION.ROLE_ID IS '角色ID，引用 SYS_ROLE.ID';
COMMENT ON COLUMN SYS_ROLE_PERMISSION.PERMISSION_ID IS '权限ID，引用 SYS_PERMISSION.ID';
COMMENT ON COLUMN SYS_ROLE_PERMISSION.CREATED_AT IS '创建时间';

CREATE TABLE SYS_AUDIT_LOG (
                               ID VARCHAR2(64) PRIMARY KEY,
                               USER_ID VARCHAR2(64),
                               ACTION VARCHAR2(128),
                               DETAIL VARCHAR2(2000),
                               IP VARCHAR2(64),
                               CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE SYS_AUDIT_LOG IS '审计日志表';
COMMENT ON COLUMN SYS_AUDIT_LOG.ID IS '主键，UUID';
COMMENT ON COLUMN SYS_AUDIT_LOG.USER_ID IS '执行操作的用户ID';
COMMENT ON COLUMN SYS_AUDIT_LOG.ACTION IS '操作类型/名称';
COMMENT ON COLUMN SYS_AUDIT_LOG.DETAIL IS '操作详情/变更内容';
COMMENT ON COLUMN SYS_AUDIT_LOG.IP IS '操作来源 IP';
COMMENT ON COLUMN SYS_AUDIT_LOG.CREATED_AT IS '创建时间';

CREATE TABLE SYS_TOKEN_BLACKLIST (
                                     JTI VARCHAR2(128) PRIMARY KEY,
                                     REVOKED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                     EXPIRES_AT TIMESTAMP
);

COMMENT ON TABLE SYS_TOKEN_BLACKLIST IS '被撤销的 token 黑名单（按 jti）';
COMMENT ON COLUMN SYS_TOKEN_BLACKLIST.JTI IS 'JWT 的 jti（主键）';
COMMENT ON COLUMN SYS_TOKEN_BLACKLIST.REVOKED_AT IS '撤销时间';
COMMENT ON COLUMN SYS_TOKEN_BLACKLIST.EXPIRES_AT IS 'Token 到期时间（可用于清理历史数据）';
