-- V3: 创建用户模块表（表名与字段使用大写，并添加表注释与字段注释）
-- Tables: SYS_USER, SYS_ROLE, SYS_USER_ROLE

CREATE TABLE SYS_USER (
                          ID VARCHAR2(64) PRIMARY KEY,
                          USERNAME VARCHAR2(128) NOT NULL,
                          PASSWORD VARCHAR2(256) NOT NULL,
                          SALT VARCHAR2(64),
                          DISPLAY_NAME VARCHAR2(128),
                          EMAIL VARCHAR2(256),
                          MOBILE VARCHAR2(32),
                          STATUS NUMBER(1) DEFAULT 1,
                          IS_SUPER NUMBER(1) DEFAULT 0,
                          CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          CREATED_BY VARCHAR2(64),
                          UPDATED_BY VARCHAR2(64)
);

CREATE UNIQUE INDEX UQ_SYS_USER_USERNAME ON SYS_USER(USERNAME);

COMMENT ON TABLE SYS_USER IS '用户表';
COMMENT ON COLUMN SYS_USER.ID IS '主键，UUID';
COMMENT ON COLUMN SYS_USER.USERNAME IS '登录用户名';
COMMENT ON COLUMN SYS_USER.PASSWORD IS '加密后的密码';
COMMENT ON COLUMN SYS_USER.SALT IS '密码盐';
COMMENT ON COLUMN SYS_USER.DISPLAY_NAME IS '展示名称/昵称';
COMMENT ON COLUMN SYS_USER.EMAIL IS '电子邮箱';
COMMENT ON COLUMN SYS_USER.MOBILE IS '手机号码';
COMMENT ON COLUMN SYS_USER.STATUS IS '用户状态，1=正常，0=禁用';
COMMENT ON COLUMN SYS_USER.IS_SUPER IS '是否为超级管理员，1=是，0=否';
COMMENT ON COLUMN SYS_USER.CREATED_AT IS '创建时间';
COMMENT ON COLUMN SYS_USER.UPDATED_AT IS '更新时间';
COMMENT ON COLUMN SYS_USER.CREATED_BY IS '创建者用户ID';
COMMENT ON COLUMN SYS_USER.UPDATED_BY IS '更新者用户ID';

CREATE TABLE SYS_ROLE (
                          ID VARCHAR2(64) PRIMARY KEY,
                          NAME VARCHAR2(128) NOT NULL,
                          CODE VARCHAR2(128) NOT NULL,
                          DESCRIPTION VARCHAR2(512),
                          CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          CREATED_BY VARCHAR2(64),
                          UPDATED_BY VARCHAR2(64)
);

CREATE UNIQUE INDEX UQ_SYS_ROLE_CODE ON SYS_ROLE(CODE);

COMMENT ON TABLE SYS_ROLE IS '角色表';
COMMENT ON COLUMN SYS_ROLE.ID IS '主键，UUID';
COMMENT ON COLUMN SYS_ROLE.NAME IS '角色名称';
COMMENT ON COLUMN SYS_ROLE.CODE IS '角色编码（唯一）';
COMMENT ON COLUMN SYS_ROLE.DESCRIPTION IS '角色描述';
COMMENT ON COLUMN SYS_ROLE.CREATED_AT IS '创建时间';
COMMENT ON COLUMN SYS_ROLE.UPDATED_AT IS '更新时间';
COMMENT ON COLUMN SYS_ROLE.CREATED_BY IS '创建者用户ID';
COMMENT ON COLUMN SYS_ROLE.UPDATED_BY IS '更新者用户ID';

CREATE TABLE SYS_USER_ROLE (
                               ID VARCHAR2(64) PRIMARY KEY,
                               USER_ID VARCHAR2(64) NOT NULL,
                               ROLE_ID VARCHAR2(64) NOT NULL,
                               CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               CREATED_BY VARCHAR2(64),
                               UPDATED_BY VARCHAR2(64)
);

CREATE UNIQUE INDEX UQ_SYS_USER_ROLE ON SYS_USER_ROLE(USER_ID, ROLE_ID);

COMMENT ON TABLE SYS_USER_ROLE IS '用户-角色关联表';
COMMENT ON COLUMN SYS_USER_ROLE.ID IS '主键，UUID';
COMMENT ON COLUMN SYS_USER_ROLE.USER_ID IS '用户ID，引用 SYS_USER.ID';
COMMENT ON COLUMN SYS_USER_ROLE.ROLE_ID IS '角色ID，引用 SYS_ROLE.ID';
COMMENT ON COLUMN SYS_USER_ROLE.CREATED_AT IS '创建时间';
COMMENT ON COLUMN SYS_USER_ROLE.UPDATED_AT IS '更新时间';
COMMENT ON COLUMN SYS_USER_ROLE.CREATED_BY IS '创建者用户ID';
COMMENT ON COLUMN SYS_USER_ROLE.UPDATED_BY IS '更新者用户ID';
