CREATE TABLE WF_PROCESS_DEF_DESIGN (
    DEF_ID VARCHAR(64) NOT NULL,
    DESIGN_JSON CLOB,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_WF_PROCESS_DEF_DESIGN PRIMARY KEY (DEF_ID)
);

COMMENT ON TABLE WF_PROCESS_DEF_DESIGN IS '流程定义设计数据表，存储可视化设计的 JSON';
COMMENT ON COLUMN WF_PROCESS_DEF_DESIGN.DEF_ID IS '流程定义 ID';
COMMENT ON COLUMN WF_PROCESS_DEF_DESIGN.DESIGN_JSON IS '设计数据 JSON';

