CREATE TABLE ST_PIPELINE (
    ID             VARCHAR(64)   NOT NULL,
    CREATED_BY     VARCHAR(64),
    UPDATED_BY     VARCHAR(64),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NAME           VARCHAR(128)  NOT NULL,
    CONFIG_FORMAT  VARCHAR(16)   DEFAULT 'hocon' NOT NULL,
    CONFIG_CONTENT CLOB,
    EXEC_MODE      VARCHAR(16)   DEFAULT 'local' NOT NULL,
    CLUSTER_NAME   VARCHAR(64),
    STATUS         INT           DEFAULT 1 NOT NULL,
    REMARK         VARCHAR(512),
    CONSTRAINT PK_ST_PIPELINE PRIMARY KEY (ID)
);

CREATE TABLE ST_EXECUTION (
    ID               VARCHAR(64)   NOT NULL,
    CREATED_BY       VARCHAR(64),
    UPDATED_BY       VARCHAR(64),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PIPELINE_ID      VARCHAR(64)   NOT NULL,
    STATUS           VARCHAR(32)   NOT NULL,
    STARTED_AT       TIMESTAMP,
    FINISHED_AT      TIMESTAMP,
    EXIT_CODE        INT,
    LOG_PATH         VARCHAR(512),
    CONFIG_PATH      VARCHAR(512),
    SEATUNNEL_JOB_ID VARCHAR(128),
    ERROR_MESSAGE    VARCHAR(1000),
    CONSTRAINT PK_ST_EXECUTION PRIMARY KEY (ID)
);

CREATE INDEX IDX_ST_EXECUTION_PIPELINE ON ST_EXECUTION (PIPELINE_ID, CREATED_AT);
CREATE INDEX IDX_ST_EXECUTION_STATUS ON ST_EXECUTION (STATUS, CREATED_AT);

COMMENT ON TABLE ST_PIPELINE IS 'SeaTunnel 采集任务（Pipeline）定义';
COMMENT ON COLUMN ST_PIPELINE.ID IS '主键ID';
COMMENT ON COLUMN ST_PIPELINE.NAME IS '任务名称';
COMMENT ON COLUMN ST_PIPELINE.CONFIG_FORMAT IS '配置格式：hocon/json';
COMMENT ON COLUMN ST_PIPELINE.CONFIG_CONTENT IS 'SeaTunnel 作业配置内容';
COMMENT ON COLUMN ST_PIPELINE.EXEC_MODE IS '执行模式：local/cluster';
COMMENT ON COLUMN ST_PIPELINE.CLUSTER_NAME IS '集群名（cluster 模式可选）';
COMMENT ON COLUMN ST_PIPELINE.STATUS IS '状态：1-启用，0-禁用';
COMMENT ON COLUMN ST_PIPELINE.REMARK IS '备注';

COMMENT ON TABLE ST_EXECUTION IS 'SeaTunnel 任务运行记录';
COMMENT ON COLUMN ST_EXECUTION.ID IS '主键ID';
COMMENT ON COLUMN ST_EXECUTION.PIPELINE_ID IS '任务ID';
COMMENT ON COLUMN ST_EXECUTION.STATUS IS '运行状态：RUNNING/SUCCESS/FAILED/CANCELLED';
COMMENT ON COLUMN ST_EXECUTION.STARTED_AT IS '开始时间';
COMMENT ON COLUMN ST_EXECUTION.FINISHED_AT IS '结束时间';
COMMENT ON COLUMN ST_EXECUTION.EXIT_CODE IS '进程退出码';
COMMENT ON COLUMN ST_EXECUTION.LOG_PATH IS '日志文件路径';
COMMENT ON COLUMN ST_EXECUTION.CONFIG_PATH IS '本次运行实际使用的配置文件路径';
COMMENT ON COLUMN ST_EXECUTION.SEATUNNEL_JOB_ID IS 'SeaTunnel 返回/解析的 JobId（若可获取）';
COMMENT ON COLUMN ST_EXECUTION.ERROR_MESSAGE IS '失败原因摘要';
