CREATE TABLE ST_DATASYNC_TASK (
    ID             VARCHAR(64)   NOT NULL,
    CREATED_BY     VARCHAR(64),
    UPDATED_BY     VARCHAR(64),
    CREATED_AT     TIMESTAMP,
    UPDATED_AT     TIMESTAMP,
    NAME           VARCHAR(128)  NOT NULL,
    SOURCE_DS_ID   VARCHAR(64)   NOT NULL,
    SOURCE_SCHEMA  VARCHAR(128),
    SOURCE_TABLE   VARCHAR(128)  NOT NULL,
    SINK_DS_ID     VARCHAR(64)   NOT NULL,
    SINK_SCHEMA    VARCHAR(128),
    SINK_TABLE     VARCHAR(128)  NOT NULL,
    SAVE_MODE      VARCHAR(32)   DEFAULT 'APPEND_DATA' NOT NULL,
    PARALLELISM    INT          DEFAULT 1 NOT NULL,
    PIPELINE_ID    VARCHAR(64),
    STATUS         INT          DEFAULT 1 NOT NULL,
    REMARK         VARCHAR(512),
    CONSTRAINT PK_ST_DATASYNC_TASK PRIMARY KEY (ID)
);

CREATE INDEX IDX_ST_DATASYNC_TASK_SOURCE ON ST_DATASYNC_TASK (SOURCE_DS_ID);
CREATE INDEX IDX_ST_DATASYNC_TASK_SINK ON ST_DATASYNC_TASK (SINK_DS_ID);
CREATE INDEX IDX_ST_DATASYNC_TASK_PIPELINE ON ST_DATASYNC_TASK (PIPELINE_ID);

COMMENT ON TABLE ST_DATASYNC_TASK IS '表到表数据同步任务（基于 SeaTunnel）';
COMMENT ON COLUMN ST_DATASYNC_TASK.NAME IS '任务名称';
COMMENT ON COLUMN ST_DATASYNC_TASK.SOURCE_DS_ID IS '源数据源ID';
COMMENT ON COLUMN ST_DATASYNC_TASK.SOURCE_SCHEMA IS '源 schema/catalog';
COMMENT ON COLUMN ST_DATASYNC_TASK.SOURCE_TABLE IS '源表名';
COMMENT ON COLUMN ST_DATASYNC_TASK.SINK_DS_ID IS '目标数据源ID';
COMMENT ON COLUMN ST_DATASYNC_TASK.SINK_SCHEMA IS '目标 schema/catalog';
COMMENT ON COLUMN ST_DATASYNC_TASK.SINK_TABLE IS '目标表名';
COMMENT ON COLUMN ST_DATASYNC_TASK.SAVE_MODE IS '写入策略：APPEND_DATA/DROP_DATA/ERROR_WHEN_DATA_EXISTS';
COMMENT ON COLUMN ST_DATASYNC_TASK.PARALLELISM IS '并行度';
COMMENT ON COLUMN ST_DATASYNC_TASK.PIPELINE_ID IS '关联 ST_PIPELINE ID';
COMMENT ON COLUMN ST_DATASYNC_TASK.STATUS IS '状态：1-启用，0-禁用';
COMMENT ON COLUMN ST_DATASYNC_TASK.REMARK IS '备注';
