CREATE TABLE WF_DEFINITION (
    ID            VARCHAR(64)   NOT NULL,
    CREATED_BY    VARCHAR(64),
    UPDATED_BY    VARCHAR(64),
    CREATED_AT    TIMESTAMP,
    UPDATED_AT    TIMESTAMP,
    CODE          VARCHAR(64)   NOT NULL,
    NAME          VARCHAR(128)  NOT NULL,
    DESCRIPTION   VARCHAR(512),
    STATUS        INT           DEFAULT 1 NOT NULL,
    VERSION_NO    INT           DEFAULT 1 NOT NULL,
    CONSTRAINT PK_WF_DEFINITION PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UQ_WF_DEFINITION_CODE ON WF_DEFINITION (CODE);
CREATE INDEX IDX_WF_DEFINITION_UPDATED_AT ON WF_DEFINITION (UPDATED_AT);

CREATE TABLE WF_DEFINITION_DESIGN (
    ID            VARCHAR(64)   NOT NULL,
    CREATED_BY    VARCHAR(64),
    UPDATED_BY    VARCHAR(64),
    CREATED_AT    TIMESTAMP,
    UPDATED_AT    TIMESTAMP,
    DEFINITION_ID VARCHAR(64)   NOT NULL,
    DESIGN_JSON   CLOB,
    VERSION_NO    INT           DEFAULT 1 NOT NULL,
    CONSTRAINT PK_WF_DEFINITION_DESIGN PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UQ_WF_DEF_DESIGN_DEFINITION ON WF_DEFINITION_DESIGN (DEFINITION_ID);
CREATE INDEX IDX_WF_DEF_DESIGN_UPDATED_AT ON WF_DEFINITION_DESIGN (UPDATED_AT);

COMMENT ON TABLE WF_DEFINITION IS '流程定义主表';
COMMENT ON COLUMN WF_DEFINITION.CODE IS '流程编码，唯一';
COMMENT ON COLUMN WF_DEFINITION.NAME IS '流程名称';
COMMENT ON COLUMN WF_DEFINITION.DESCRIPTION IS '流程描述';
COMMENT ON COLUMN WF_DEFINITION.STATUS IS '状态：1启用，0禁用';
COMMENT ON COLUMN WF_DEFINITION.VERSION_NO IS '版本号';

COMMENT ON TABLE WF_DEFINITION_DESIGN IS '流程可视化设计JSON';
COMMENT ON COLUMN WF_DEFINITION_DESIGN.DEFINITION_ID IS '流程定义ID';
COMMENT ON COLUMN WF_DEFINITION_DESIGN.DESIGN_JSON IS '设计器JSON数据';
COMMENT ON COLUMN WF_DEFINITION_DESIGN.VERSION_NO IS '设计版本号';

