-- V8: 创建站内信模块表

CREATE TABLE SYS_NOTIFICATION (
    ID VARCHAR2(64) PRIMARY KEY,
    USER_ID VARCHAR2(64) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    BIZ_TYPE VARCHAR2(64),
    BIZ_ID VARCHAR2(128),
    IS_READ NUMBER(1) DEFAULT 0,
    READ_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(64),
    UPDATED_BY VARCHAR2(64)
);

CREATE INDEX IDX_SYS_NOTIFICATION_USER_READ ON SYS_NOTIFICATION(USER_ID, IS_READ, CREATED_AT);
CREATE INDEX IDX_SYS_NOTIFICATION_USER_CREATED ON SYS_NOTIFICATION(USER_ID, CREATED_AT);

COMMENT ON TABLE SYS_NOTIFICATION IS '站内信消息表';
COMMENT ON COLUMN SYS_NOTIFICATION.ID IS '主键，UUID';
COMMENT ON COLUMN SYS_NOTIFICATION.USER_ID IS '接收用户ID';
COMMENT ON COLUMN SYS_NOTIFICATION.TITLE IS '消息标题';
COMMENT ON COLUMN SYS_NOTIFICATION.CONTENT IS '消息内容';
COMMENT ON COLUMN SYS_NOTIFICATION.BIZ_TYPE IS '业务类型';
COMMENT ON COLUMN SYS_NOTIFICATION.BIZ_ID IS '业务主键';
COMMENT ON COLUMN SYS_NOTIFICATION.IS_READ IS '是否已读，1=已读，0=未读';
COMMENT ON COLUMN SYS_NOTIFICATION.READ_AT IS '已读时间';
COMMENT ON COLUMN SYS_NOTIFICATION.CREATED_AT IS '创建时间';
COMMENT ON COLUMN SYS_NOTIFICATION.UPDATED_AT IS '更新时间';
COMMENT ON COLUMN SYS_NOTIFICATION.CREATED_BY IS '创建者用户ID';
COMMENT ON COLUMN SYS_NOTIFICATION.UPDATED_BY IS '更新者用户ID';

