-- V9: 文件上传平台（分片/断点续传/加密存储）

CREATE TABLE SYS_FILE_OBJECT (
    ID VARCHAR2(64) PRIMARY KEY,
    FILE_MD5 VARCHAR2(32) NOT NULL,
    FILE_NAME VARCHAR2(512) NOT NULL,
    CONTENT_TYPE VARCHAR2(128),
    FILE_SIZE NUMBER(20) NOT NULL,
    CHUNK_SIZE NUMBER(20) NOT NULL,
    TOTAL_CHUNKS NUMBER(10) NOT NULL,
    STORAGE_PATH VARCHAR2(1024) NOT NULL,
    STORAGE_SIZE NUMBER(20) NOT NULL,
    ENCRYPT_ALGORITHM VARCHAR2(64) NOT NULL,
    CIPHER_IV VARCHAR2(64) NOT NULL,
    WRAP_IV VARCHAR2(64) NOT NULL,
    WRAPPED_DEK VARCHAR2(512) NOT NULL,
    STATUS NUMBER(1) DEFAULT 1,
    UPLOAD_COUNT NUMBER(10) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(64),
    UPDATED_BY VARCHAR2(64)
);

CREATE UNIQUE INDEX UK_SYS_FILE_OBJECT_MD5 ON SYS_FILE_OBJECT(FILE_MD5);
CREATE INDEX IDX_SYS_FILE_OBJECT_CREATED ON SYS_FILE_OBJECT(CREATED_AT);

CREATE TABLE SYS_FILE_UPLOAD_SESSION (
    ID VARCHAR2(64) PRIMARY KEY,
    UPLOAD_ID VARCHAR2(64) NOT NULL,
    FILE_MD5 VARCHAR2(32) NOT NULL,
    FILE_NAME VARCHAR2(512) NOT NULL,
    CONTENT_TYPE VARCHAR2(128),
    FILE_SIZE NUMBER(20) NOT NULL,
    CHUNK_SIZE NUMBER(20) NOT NULL,
    TOTAL_CHUNKS NUMBER(10) NOT NULL,
    UPLOADED_CHUNKS NUMBER(10) DEFAULT 0,
    STATUS NUMBER(1) DEFAULT 0,
    FILE_OBJECT_ID VARCHAR2(64),
    LAST_CHUNK_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(64),
    UPDATED_BY VARCHAR2(64)
);

CREATE UNIQUE INDEX UK_SYS_FILE_UPLOAD_ID ON SYS_FILE_UPLOAD_SESSION(UPLOAD_ID);
CREATE INDEX IDX_SYS_FILE_UPLOAD_MD5 ON SYS_FILE_UPLOAD_SESSION(FILE_MD5, STATUS, UPDATED_AT);

CREATE TABLE SYS_FILE_CHUNK (
    ID VARCHAR2(64) PRIMARY KEY,
    UPLOAD_ID VARCHAR2(64) NOT NULL,
    CHUNK_INDEX NUMBER(10) NOT NULL,
    CHUNK_SIZE NUMBER(20) NOT NULL,
    CHUNK_MD5 VARCHAR2(32),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(64),
    UPDATED_BY VARCHAR2(64)
);

CREATE UNIQUE INDEX UK_SYS_FILE_CHUNK_IDX ON SYS_FILE_CHUNK(UPLOAD_ID, CHUNK_INDEX);
CREATE INDEX IDX_SYS_FILE_CHUNK_UPLOAD ON SYS_FILE_CHUNK(UPLOAD_ID);

COMMENT ON TABLE SYS_FILE_OBJECT IS '文件管理对象表（MD5全局唯一，物理去重）';
COMMENT ON TABLE SYS_FILE_UPLOAD_SESSION IS '文件上传会话表（断点续传）';
COMMENT ON TABLE SYS_FILE_CHUNK IS '文件分片上传记录表';

